hmrc/cgt-calculator-resident-properties-frontend

app/controllers/ReportController.scala
app/views/calculation/resident/properties/report/deductionsSummaryReport.scala.html
app/views/calculation/resident/properties/summary/deductionsSummary.scala.html
test/controllers/resident/properties/ReportControllerSpec/DeductionsSummaryActionSpec.scala
test/views/resident/properties/report/PropertiesDeductionsReportViewSpec.scala

MERGE AFTER CGT-3059 and CGT-3049

Added summary partial to deductions pdf.

---

app/views/calculation/resident/properties/gain/improvements.scala.html
conf/messages
test/assets/MessageLookup.scala
test/views/resident/properties/gain/ImprovementsViewSpec.scala

Whenever this is done can the merger please un-block and move CGT-2490

Added the JO content to improvements.

---

app/views/calculation/resident/properties/gain/improvements.scala.html
app/views/helpers/expandableHelpTextHelper.scala.html
test/views/resident/properties/gain/ImprovementsViewSpec.scala

This also fixes a long-standing bug with the panel width and colours of drop-downs in the project.

Moved the progressive disclosure on Improvements

---

app/controllers/DeductionsController.scala
app/controllers/IncomeController.scala
app/controllers/WhatNextSAController.scala

Will perf test and deploy on Monday

DDCNLS-1582: a none.get slipped through overnight, this should fix

---

conf/messages
test/assets/MessageLookup.scala

@nehadotkannaujia - Rebasing message replaced; unit tests updated

DDCNLS-1863

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
project/MicroService.scala
project/frontendBuild.scala
project/plugins.sbt

Updating cgt-calculator-resident-properties-frontend to new build

DL-1242 - Migrating to new build

---

app/config/ApplicationConfig.scala
app/controllers/FeedbackSurveyController.scala
app/views/calculation/resident/properties/whatNext/whatNextNonSaGain.scala.html
app/views/calculation/resident/properties/whatNext/whatNextSaGain.scala.html
app/views/calculation/resident/properties/whatNext/whatNextSaNoGain.scala.html
conf/app.routes
conf/application.conf
conf/messages.cy
conf/messages.en
project/frontendBuild.scala
test/assets/MessageLookup.scala
test/controllers/WhatNextNonSaControllerSpec.scala
test/controllers/resident/properties/WhatNextSaControllerSpec.scala
test/controllers/resident/properties/feedbackSurveyControllerSpec.scala
test/views/resident/properties/whatNext/WhatNextNonSaGainViewSpec.scala
test/views/resident/properties/whatNext/WhatNextSAGainViewSpec.scala
test/views/resident/properties/whatNext/WhatNextSANoGainViewSpec.scala

** Implement feedback survey **
Implement feedback survey and test changes

DL-920 Implementing feedback survey and test changes

---

app/config/ApplicationConfig.scala
conf/application.conf
project/frontendBuild.scala
project/plugins.sbt

**New feature**
App config change.

DL-1813: Switched to new feedback frontend service.

---

app/config/frontendGlobal.scala

**Maintenance fix**
We have bee observing a number of errors during monitoring for this repository and did some initial checking around the issue. It appears that there is no graceful handling of Server errors within this repo when compared with the other CGT frontend applications. Identified that onServerError had not been included. Added to the frontendGlobal config for initial review.

NoneGetIssue adding missing server error handling to repoistory

---

app/config/ApplicationConfig.scala
app/views/govuk_wrapper.scala.html
conf/application.conf
project/frontendBuild.scala

DL-1404 
Google Tag Manager Integration
Included Google Tag Manager integration according to epic issue DL-1411. Google Analytics is unchanged while Google Tag Manager has been stubbed with an id of 'N/A' for the time being.

Dl 1404 - CGT Google Tag Manager (GTM) Migration

---

conf/application.conf

Update DFS link

---

build.sbt

DL-2807 - Disabled jUnit XML report plugin causing pipeline to fail

---

project/AppDependencies.scala

DL-2411 revert mongo caching

---

app/views/helpers/gainSummaryPartial.scala.html
public/stylesheets/cgt.css

- [X ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure

DL-2904 - CGT - Accessibility Fixes

---

project/AppDependencies.scala
project/build.properties
project/plugins.sbt

DL-3526 Updating dependencies

---

project/AppDependencies.scala
project/build.properties
project/plugins.sbt

DL-3736
Dependency updates to raise simple-reactivemongo version

DL-3736 Updating dependencies for simple-reactivemongo uplift

---

conf/application.conf
project/AppDependencies.scala

DL-4259 - A11y statement functionality for CGT-RES-PROP

---

app/controllers/ReportController.scala

**New feature**
Logger added to aid investigation

DL-4355 Logger added for host used in pdf generation

---

app/config/ApplicationConfig.scala
app/controllers/SaUserController.scala
app/controllers/WhatNextNonSaController.scala
app/forms/resident/SaUserForm.scala
app/services/SessionCacheService.scala
app/views/calculation/resident/properties/whatNext/whatNextNonSaGain.scala.html
app/views/calculation/resident/properties/whatNext/whatNextNonSaLoss.scala.html
conf/application.conf
test/controllers/WhatNextNonSaControllerSpec.scala
test/controllers/resident/properties/SaUserControllerSpec.scala
test/services/SessionCacheServiceSpec.scala
test/views/resident/properties/whatNext/WhatNextNonSaGainViewSpec.scala
test/views/resident/properties/whatNext/WhatNextNonSaLossViewSpec.scala

DL-4338 - Make Self Assessment screen optional

---

.bsp/sbt.json
app/config/CalculatorSessionCache.scala
app/config/ServicesBindings.scala
app/connectors/SessionCacheConnector.scala
app/controllers/CgtLanguageController.scala
app/controllers/DeductionsController.scala
app/controllers/FeedbackSurveyController.scala
app/controllers/GainController.scala
app/controllers/IncomeController.scala
app/controllers/PropertiesController.scala
app/controllers/ReportController.scala
app/controllers/SaUserController.scala
project/AppDependencies.scala

There are still some warning present when compiling code that I havent been able to clear. Might be worth creating ticket to remove those warnings.

DL-4894 - removed unused dependency and fixed some warnings

---

.gitignore
app/config/ServicesBindings.scala
app/connectors/CalculatorConnector.scala
app/connectors/SessionCacheConnector.scala
build.sbt
project/AppDependencies.scala
project/plugins.sbt
test/common/CommonPlaySpec.scala

DL-4885 Fixing warnings and updating dependencies

---

app/common/Dates.scala
app/views/helpers/resident/summaryDateRowHelper.scala.html

DL-5109 - CGT: Summary page displays an incorrect year

---

.gitignore
app/connectors/SessionCacheConnector.scala
app/views/calculation/resident/properties/deductions/propertyLivedIn.scala.html
app/views/calculation/resident/properties/gain/buyForLess.scala.html
app/views/calculation/resident/properties/gain/howBecameOwner.scala.html
app/views/calculation/resident/properties/gain/whoDidYouGiveItTo.scala.html
app/views/calculation/resident/properties/whatNext/saUser.scala.html
app/views/helpers/errorSummary.scala.html
build.sbt
project/AppDependencies.scala
project/plugins.sbt

DL-5746 Play 2.8 upgrade

---

app/views/Layout.scala.html
app/views/calculation/resident/properties/gain/disposalDate.scala.html
app/views/calculation/resident/properties/gain/sellOrGiveAway.scala.html
app/views/calculation/resident/properties/introduction.scala.html
app/views/playHelpers/backLink.scala.html
app/views/playHelpers/inputRadio.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/SellOrGiveAwayActionSpec.scala
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala
test/views/resident/properties/gain/DisposalDateViewSpec.scala
test/views/resident/properties/gain/SellOrGiveAwayViewSpec.scala

**New feature**
Updated the sell-or-give-away page to use the new components
Added a new component for radio inputs that used the new UI
Updated the current back button in Layout.scala to incorporate a href rather than using java history

DL-8259 sell-or-give-away

---

app/views/calculation/resident/properties/gain/sellForLess.scala.html
app/views/calculation/resident/properties/gain/sellOrGiveAway.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/SellForLessActionSpec.scala
test/views/resident/properties/gain/SellForLessViewSpec.scala

DL-8260 - sell-for-less

---

app/views/calculation/resident/properties/gain/ownerBeforeLegislationStart.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/OwnerBeforeLegislationStartActionSpec.scala
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala
test/views/resident/properties/gain/OwnerBeforeLegislationStartViewSpec.scala

DL-8263 owner-before-legislation-start

---

app/views/calculation/resident/properties/gain/worthWhenSoldForLess.scala.html
app/views/playHelpers/formInputMoney.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/WorthWhenSoldForLessActionSpec.scala
test/views/resident/properties/gain/WorthWhenSoldForLessViewSpec.scala

DL-8261 worthWhenSoldForLess.scala

---

app/views/calculation/resident/properties/gain/disposalCosts.scala.html
test/controllers/resident/properties/GainControllerSpec/DisposalCostsActionSpec.scala
test/views/resident/properties/gain/DisposalCostsViewSpec.scala

DL-8262 - disposalCosts

---

app/views/calculation/resident/properties/gain/acquisitionCosts.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/AcquisitionCostsActionSpec.scala
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala
test/views/resident/properties/gain/AcquisitionCostsViewSpec.scala

DL-8265 acquisition-costs

---

app/views/calculation/resident/properties/gain/valueBeforeLegislationStart.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/ValueBeforeLegislationStartActionSpec.scala
test/views/resident/properties/gain/ValueBeforeLegislationStartViewSpec.scala

DL-8264 valueBeforeLegislationStart.scala

---

app/controllers/GainController.scala
app/views/calculation/resident/properties/gain/noTaxToPay.scala.html
test/controllers/resident/properties/GainControllerSpec/NoTaxToPayActionSpec.scala
test/views/resident/properties/gain/NoTaxToPayViewSpec.scala

DL-8268 no-tax-to-pay

---

app/views/calculation/resident/properties/gain/worthWhenGaveAway.scala.html
test/controllers/resident/properties/GainControllerSpec/WorthWhenGaveAwayActionSpec.scala
test/views/resident/properties/gain/WorthWhenGaveAwayViewSpec.scala

DL-8269 - worth-when-gave-away

---

app/views/calculation/resident/properties/gain/improvements.scala.html
app/views/playHelpers/expandableHelpTextHelper.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/ImprovementsActionSpec.scala
test/views/resident/properties/gain/ImprovementsViewSpec.scala

DL-8266 improvements

---

app/views/Layout.scala.html
app/views/calculation/resident/properties/gain/howBecameOwner.scala.html
app/views/calculation/resident/properties/introduction.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/HowBecameOwnerActionSpec.scala
test/views/resident/properties/gain/HowBecameOwnerViewSpec.scala

DL-8270 how-became-owner and technical helper

---

app/views/calculation/resident/properties/gain/worthWhenInherited.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/WorthWhenInheritedActionSpec.scala
test/views/resident/properties/gain/WorthWhenInheritedViewSpec.scala

DL-8274 woth when inherited

---

app/views/calculation/resident/properties/gain/buyForLess.scala.html
test/controllers/resident/properties/GainControllerSpec/BoughtForLessThanWorthActionSpec.scala
test/views/resident/properties/gain/BoughtForLessThanWorthViewSpec.scala

DL-8271 - buyForLess

---

app/views/calculation/resident/properties/gain/worthWhenGifted.scala.html
test/controllers/resident/properties/GainControllerSpec/WorthWhenGiftedActionSpec.scala
test/views/resident/properties/gain/WorthWhenGiftedViewSpec.scala

DL-8275 - worthWhenGifted

---

app/views/calculation/resident/properties/gain/disposalValue.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/DisposalValueActionSpec.scala
test/views/resident/properties/gain/DisposalValueViewSpec.scala

DL-8276 disposalValue.scala

---

app/views/calculation/resident/properties/whatNext/saUser.scala.html
test/assets/MessageLookup.scala
test/views/resident/properties/whatNext/SaUserViewSpec.scala

DL-8279 saUser.scala

---

app/views/calculation/resident/properties/whatNext/whatNextSaNoGain.scala.html
conf/messages.cy
test/controllers/resident/properties/WhatNextSaControllerSpec.scala
test/views/resident/properties/whatNext/WhatNextSANoGainViewSpec.scala

DL-8280 - whatNextSaNoGain

---

app/views/calculation/resident/properties/whatNext/whatNextSaGain.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/WhatNextSaControllerSpec.scala
test/views/resident/properties/whatNext/WhatNextSAGainViewSpec.scala

DL-8282 whatNextSaGain.scala.html

---

app/views/calculation/resident/properties/gain/worthWhenBoughtForLess.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/WorthWhenBoughtForLessActionSpec.scala
test/views/resident/properties/gain/WorthWhenBoughtForLessViewSpec.scala

DL-8272 worthWhenBoughtForLess.scala.html

---

app/views/calculation/resident/properties/whatNext/whatNextNonSaLoss.scala.html
test/assets/MessageLookup.scala
test/controllers/WhatNextNonSaControllerSpec.scala
test/views/resident/properties/whatNext/WhatNextNonSaLossViewSpec.scala

DL-8281 whatNextNonSaLoss.scala

---

app/views/calculation/resident/properties/income/currentIncome.scala.html
test/assets/MessageLookup.scala
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala
test/views/resident/properties/income/CurrentIncomeViewSpec.scala

DL-8286 current-incone

---

app/views/calculation/resident/properties/whatNext/whatNextNonSaGain.scala.html
test/assets/MessageLookup.scala
test/controllers/WhatNextNonSaControllerSpec.scala
test/views/resident/properties/whatNext/WhatNextNonSaGainViewSpec.scala

DL-8283 whatNextNonSaGain.scala.html

---

app/views/calculation/resident/properties/whatNext/whatNextSAFourTimesAEA.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/WhatNextSaControllerSpec.scala
test/views/resident/properties/whatNext/WhatNextSAFourTimesAEAViewSpec.scala

DL-8284 whatNextSAFourTimesAEA.scala

---

app/views/calculation/resident/properties/deductions/lettingsRelief.scala.html
test/controllers/resident/properties/DeductionsControllerSpec/LettingsReliefActionSpec.scala
test/views/resident/properties/deductions/LettingsReliefViewSpec.scala

DL-8287 - lettingsRelief

---

app/views/calculation/resident/properties/report/deductionsSummaryReport.scala.html
app/views/calculation/resident/properties/report/finalSummaryReport.scala.html
app/views/calculation/resident/properties/report/gainSummaryReport.scala.html
app/views/playHelpers/checkYourAnswersPartial.scala.html
app/views/playHelpers/deductionsSummaryPartial.scala.html
app/views/playHelpers/finalSummaryPartial.scala.html
app/views/playHelpers/gainSummaryPartial.scala.html
app/views/playHelpers/resident/summaryDateRowHelper.scala.html
app/views/playHelpers/resident/summaryNumericRow.scala.html
app/views/playHelpers/resident/summaryNumericRowHelper.scala.html
app/views/playHelpers/resident/summaryOptionRowHelper.scala.html
app/views/playHelpers/resident/summaryTextRowHelper.scala.html
test/views/resident/properties/report/PropertiesDeductionsReportViewSpec.scala
test/views/resident/properties/report/PropertiesGainReportViewSpec.scala

DL-8285 - 3 x report pdf

---

app/views/calculation/resident/properties/deductions/lettingsReliefValue.scala.html
test/assets/MessageLookup.scala
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala
test/views/resident/properties/deductions/LettingsReliefValueViewSpec.scala

DL-8288 lettings-relief-value

---

app/views/calculation/resident/properties/deductions/privateResidenceRelief.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/DeductionsControllerSpec/PrivateResidenceReliefActionSpec.scala
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala
test/views/resident/properties/deductions/PrivateResidenceReliefViewSpec.scala

DL-8289 - private-residence-relief

---

app/views/Layout.scala.html
conf/application.conf

DL-8362 - Get help link not showing in welsh

---

app/views/calculation/resident/properties/deductions/propertyLivedIn.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/DeductionsControllerSpec/PropertyLivedInActionSpec.scala
test/views/resident/properties/deductions/PropertyLivedInViewSpec.scala

DL-8291 propertyLivedIn.scala

---

app/views/calculation/resident/properties/deductions/privateResidenceReliefValue.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/DeductionsControllerSpec/PrivateResidenceReliefValueActionSpec.scala
test/views/resident/properties/deductions/PrivateResidenceReliefValueViewSpec.scala

DL-8290 privateResidenceReliefValue.scala

---

app/views/calculation/resident/personalAllowance.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/IncomeControllerSpec/PersonalAllowanceActionSpec.scala
test/views/resident/PersonalAllowanceViewSpec.scala

DL-8378 personalAllowance.scala

---

app/views/calculation/resident/outsideTaxYear.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/OutsideTaxYearsActionSpec.scala
test/views/resident/OutsideTaxYearsViewSpec.scala

DL-8379 outsideTaxYear.scala

---

app/views/calculation/resident/lossesBroughtForwardValue.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/DeductionsControllerSpec/LossesBroughtForwardValueActionSpec.scala
test/views/resident/LossesBroughtForwardValueViewSpec.scala
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala

DL-8381 losses-brought-forward-value

---

app/views/calculation/resident/lossesBroughtForward.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/DeductionsControllerSpec/LossesBroughtForwardActionSpec.scala
test/controllers/resident/properties/IncomeControllerSpec/PersonalAllowanceActionSpec.scala
test/views/resident/LossesBroughtForwardViewSpec.scala
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala

DL-8380 lossesBroughtForward.scala

---

app/views/calculation/resident/properties/introduction.scala.html

DL-8360 updated button for acceptance test

---

app/views/calculation/resident/properties/deductions/lettingsRelief.scala.html
app/views/calculation/resident/properties/deductions/privateResidenceRelief.scala.html
app/views/calculation/resident/properties/deductions/privateResidenceReliefValue.scala.html
app/views/calculation/resident/properties/introduction.scala.html
app/views/calculation/resident/properties/summary/deductionsSummary.scala.html
app/views/calculation/resident/properties/summary/finalSummary.scala.html
app/views/calculation/resident/properties/summary/gainSummary.scala.html
app/views/calculation/resident/properties/whatNext/whatNextNonSaGain.scala.html
app/views/calculation/resident/properties/whatNext/whatNextNonSaLoss.scala.html
app/views/calculation/resident/properties/whatNext/whatNextSAFourTimesAEA.scala.html
app/views/calculation/resident/properties/whatNext/whatNextSaGain.scala.html
app/views/calculation/resident/properties/whatNext/whatNextSaNoGain.scala.html
app/views/playHelpers/resident/summaryDateRowHelper.scala.html
app/views/playHelpers/resident/summaryNumericRowHelper.scala.html
app/views/playHelpers/resident/summaryOptionRowHelper.scala.html
app/views/playHelpers/resident/summaryTextRowHelper.scala.html
test/views/resident/properties/whatNext/WhatNextNonSaLossViewSpec.scala

DL-8444 added govuk-body to hyperlinks

---

app/views/calculation/resident/properties/deductions/lettingsRelief.scala.html
app/views/calculation/resident/properties/deductions/privateResidenceRelief.scala.html
app/views/calculation/resident/properties/gain/acquisitionCosts.scala.html
app/views/calculation/resident/properties/gain/disposalCosts.scala.html
app/views/calculation/resident/properties/gain/improvements.scala.html
app/views/calculation/resident/properties/gain/valueBeforeLegislationStart.scala.html
app/views/calculation/resident/properties/gain/worthWhenBoughtForLess.scala.html
app/views/calculation/resident/properties/gain/worthWhenGifted.scala.html
test/views/resident/properties/deductions/LettingsReliefViewSpec.scala
test/views/resident/properties/gain/AcquisitionCostsViewSpec.scala
test/views/resident/properties/gain/DisposalCostsViewSpec.scala
test/views/resident/properties/gain/ImprovementsViewSpec.scala
test/views/resident/properties/gain/ValueBeforeLegislationStartViewSpec.scala
test/views/resident/properties/gain/WorthWhenBoughtForLessViewSpec.scala
test/views/resident/properties/gain/WorthWhenGiftedViewSpec.scala

DL-8446 Changes from hint to body text

---

app/views/calculation/resident/personalAllowance.scala.html
app/views/calculation/resident/properties/deductions/privateResidenceRelief.scala.html
conf/messages.cy
conf/messages.en
test/assets/MessageLookup.scala

DL-8442 Changed wording on externel links

---

app/views/playHelpers/deductionsSummaryPartial.scala.html
app/views/playHelpers/finalSummaryPartial.scala.html
app/views/playHelpers/gainSummaryPartial.scala.html
test/views/resident/helpers/DeductionsSummaryPartialViewSpec.scala
test/views/resident/helpers/FinalSummaryPartialViewSpec.scala
test/views/resident/helpers/GainSummaryPartialViewSpec.scala
test/views/resident/properties/report/PropertiesFinalReportViewSpec.scala
test/views/resident/properties/summary/PropertiesDeductionsSummaryViewSpec.scala
test/views/resident/properties/summary/PropertiesFinalSummaryViewSpec.scala
test/views/resident/properties/summary/PropertiesGainSummaryViewSpec.scala

DL-8449 - Swap amount and confirmation text

---

app/assets/stylesheets/cgt-calculator-resident-properties.css

DL-8448 made questions in check answers page bold

---

conf/messages.cy
conf/messages.en
test/assets/MessageLookup.scala
test/views/resident/properties/summary/PropertiesFinalSummaryViewSpec.scala
test/views/resident/properties/summary/PropertiesGainSummaryViewSpec.scala

DL-8450 changed what to do next content

---

app/forms/resident/LossesBroughtForwardForm.scala
app/views/calculation/resident/lossesBroughtForward.scala.html
app/views/calculation/resident/lossesBroughtForwardValue.scala.html
app/views/calculation/resident/outsideTaxYear.scala.html
app/views/calculation/resident/personalAllowance.scala.html
app/views/calculation/resident/properties/income/currentIncome.scala.html
app/views/playHelpers/checkYourAnswersPartial.scala.html
conf/messages.cy
conf/messages.en
test/controllers/resident/properties/DeductionsControllerSpec/LossesBroughtForwardActionSpec.scala
test/controllers/resident/properties/DeductionsControllerSpec/LossesBroughtForwardValueActionSpec.scala
test/controllers/resident/properties/IncomeControllerSpec/CurrentIncomeActionSpec.scala
test/controllers/resident/properties/IncomeControllerSpec/PersonalAllowanceActionSpec.scala
test/views/resident/LossesBroughtForwardValueViewSpec.scala
test/views/resident/LossesBroughtForwardViewSpec.scala
test/views/resident/OutsideTaxYearsViewSpec.scala
test/views/resident/PersonalAllowanceViewSpec.scala
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala
test/views/resident/properties/income/CurrentIncomeViewSpec.scala

DL-8445 Changes slashes to 'to' in dates

---

project/AppDependencies.scala

DL-8570 Updated test dependency scope

---

conf/messages.cy
conf/messages.en
test/assets/MessageLookup.scala

DL-7658 changed message content for future years

---

app/views/calculation/resident/lossesBroughtForward.scala.html
app/views/calculation/resident/properties/income/currentIncome.scala.html
test/views/resident/LossesBroughtForwardViewSpec.scala
test/views/resident/properties/income/CurrentIncomeViewSpec.scala

DL-9069 - Changed hint text to body text

---

app/views/calculation/resident/outsideTaxYear.scala.html
conf/messages.cy
conf/messages.en
test/assets/MessageLookup.scala
test/controllers/resident/properties/GainControllerSpec/OutsideTaxYearsActionSpec.scala
test/views/resident/OutsideTaxYearsViewSpec.scala

DL-7658 - changed message content for future years

---

conf/messages.cy

DL-9177: Update welsh

---

build.sbt
conf/application.conf
project/AppDependencies.scala
test/views/resident/properties/summary/PropertiesFinalSummaryViewSpec.scala
test/views/resident/properties/summary/PropertiesGainSummaryViewSpec.scala

DL-10006 removed targetJvm

---

README.md

DL-9879 Update README.md

---

app/views/calculation/resident/lossesBroughtForward.scala.html
conf/application.conf

DL-11597 Updating legend on lossesBroughtForward page

---

app/views/playHelpers/resident/summaryTextRowHelper.scala.html
test/views/resident/helpers/CheckYourAnswersPartialViewSpec.scala

DL-11599 removed duplicate ID's

---

conf/application.conf
project/AppDependencies.scala

DL-11781 Updating Dependencies

---

app/connectors/CalculatorConnector.scala
app/views/playHelpers/deductionsSummaryPartial.scala.html
app/views/playHelpers/finalSummaryPartial.scala.html
app/views/playHelpers/gainSummaryPartial.scala.html
project/AppDependencies.scala
test/connectors/CalculatorConnectorSpec.scala

DL-11990 remove jodatime

---

app/controllers/DeductionsController.scala
app/controllers/GainController.scala
app/controllers/IncomeController.scala
app/controllers/ReportController.scala
app/controllers/ReviewAnswersController.scala
app/controllers/SaUserController.scala
app/controllers/SummaryController.scala
app/controllers/WhatNextSAController.scala
app/views/calculation/resident/properties/report/deductionsSummaryReport.scala.html
app/views/calculation/resident/properties/report/finalSummaryReport.scala.html
app/views/calculation/resident/properties/report/gainSummaryReport.scala.html
app/views/calculation/resident/properties/summary/deductionsSummary.scala.html
app/views/calculation/resident/properties/summary/finalSummary.scala.html
app/views/calculation/resident/properties/summary/gainSummary.scala.html
test/assets/MessageLookup.scala
test/controllers/RecoverableFutureSpec.scala
test/controllers/resident/properties/SummaryActionSpec.scala
test/views/resident/properties/report/PropertiesDeductionsReportViewSpec.scala
test/views/resident/properties/report/PropertiesFinalReportViewSpec.scala
test/views/resident/properties/report/PropertiesGainReportViewSpec.scala
test/views/resident/properties/summary/PropertiesDeductionsSummaryViewSpec.scala
test/views/resident/properties/summary/PropertiesFinalSummaryViewSpec.scala
test/views/resident/properties/summary/PropertiesGainSummaryViewSpec.scala

DL-11596 updated title on summary page

---

app/views/calculation/resident/properties/deductions/propertyLivedIn.scala.html
test/assets/MessageLookup.scala
test/controllers/resident/properties/DeductionsControllerSpec/PropertyLivedInActionSpec.scala

Dls 9409 add error prefix

---

app/views/calculation/resident/outsideTaxYear.scala.html

https://jira.tools.tax.service.gov.uk/browse/DLS-9397

DLS-9397 update link with proper button attributes

---

app/views/playHelpers/finalSummaryPartial.scala.html
app/views/playHelpers/resident/summaryNumericRow.scala.html
test/views/resident/helpers/FinalSummaryPartialViewSpec.scala
test/views/resident/properties/summary/PropertiesFinalSummaryViewSpec.scala

https://jira.tools.tax.service.gov.uk/browse/DLS-9696
Changing ID's to unique references to avoid duplication

DLS-9696 Duplicate IDs in table

---

app/views/playHelpers/finalSummaryPartial.scala.html
test/views/resident/helpers/FinalSummaryPartialViewSpec.scala
test/views/resident/properties/summary/PropertiesFinalSummaryViewSpec.scala

**Bug fix**
updated text to paragraph

DLS-9415 updated text to paragraph

---

conf/messages.cy
conf/messages.en
test/assets/MessageLookup.scala

[DLS-9853]Bug fix

---

project/AppDependencies.scala

[DLS-10010] Tudor Crown update

---

app/views/calculation/resident/properties/gain/worthWhenSoldForLess.scala.html

The error summary is in the wrong location.
This PR moves the position of the error message above the H1

DLS-9852 - Moved the error message above the H2

---

app/views/playHelpers/deductionsSummaryPartial.scala.html
app/views/playHelpers/finalSummaryPartial.scala.html
app/views/playHelpers/gainSummaryPartial.scala.html
build.sbt
conf/logback.xml
project/build.properties
project/plugins.sbt

suppressed route warnings and addressed none exhaustive matches.

DLS-10610 - addressing compilation warnings

---

project/AppDependencies.scala
test/connectors/CalculatorConnectorSpec.scala
test/util/WireMockMethods.scala

DLS-10784 - Port Connector tests from http to use wiremock
Ignored some tests due to use of  Option which requires tidy up the connector itself. As agreed this is covered as part of HttpV2 upgrade

DLS-10784/Shivangi/Port_to_wiremock

---

test/connectors/CalculatorConnectorSpec.scala

Hugo/DLS-11673: Correction of CalculatorConnectorSpec endpoint testing
